Galerkin4GT: /home/pol/src/GridTools/galerkin4gt_master/examples/dg_advection.cpp File Reference
dg_advection.cpp File Reference
#include "../numerics/assembly_dg.hpp"
#include "../numerics/tensor_product_element.hpp"
#include "../functors/matvec.hpp"
#include "../functors/assign.hpp"
#include "../tools/io.hpp"
Data Structures
struct gdl::bc_functor
struct flux
[assembly]
struct gdl::residual
Namespaces
gdl
[assembly]
Macros
#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#define BOOST_MPL_LIMIT_VECTOR_SIZE FUSION_MAX_VECTOR_SIZE
#define FUSION_MAX_MAP_SIZE FUSION_MAX_VECTOR_SIZE
#define FUSION_MAX_VECTOR_SIZE 40
#define HAVE_INTREPID_DEBUG
#define PEDANTIC_DISABLED
Functions
int main (int argc, char **argv)
Macro Definition Documentation
BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
BOOST_MPL_LIMIT_VECTOR_SIZE
#define BOOST_MPL_LIMIT_VECTOR_SIZE FUSION_MAX_VECTOR_SIZE
FUSION_MAX_MAP_SIZE
#define FUSION_MAX_MAP_SIZE FUSION_MAX_VECTOR_SIZE
FUSION_MAX_VECTOR_SIZE
#define FUSION_MAX_VECTOR_SIZE 40
HAVE_INTREPID_DEBUG
#define HAVE_INTREPID_DEBUG
PEDANTIC_DISABLED
#define PEDANTIC_DISABLED
Function Documentation
main()
int main (int argc, char ** argv)
[definitions]
[boundary]
[definitions]
[as_instantiation]
[as_instantiation]
[grid]
[instantiation_stiffness]
[placeholders]
[placeholders]
[computation]
boundary condition computation
[computation]
References gdl::intrepid::discretization< FE, Cub >::compute(), d1, d2, d3, gdl::spy(), and gdl::spy_vec().