Galerkin4GT: gdl::intrepid Namespace Reference
gdl::intrepid Namespace Reference
Data Structures
class boundary_cub
class boundary_discr
discretization of the boundary entities
struct discretization
defining the finite element discretization
struct geometry
discretization of the local-to-global map, structured mesh case (allowing dof ordering)
struct unstructured_geometry
discretization of the local-to-global map
Typedefs
typedef layout_tt< 3 > layout3_t
typedef layout_tt< 4 > layout4_t
Functions
template<typename Geometry , typename FEBackend , typename MatrixType >
bool test (assembly_base< Geometry > &assembly_base_, assembly< Geometry > &assembly_, FEBackend const &fe_backend_, MatrixType const &stiffness_)
template<typename Geometry , typename FEBackend , typename MatrixType >
bool test_mass (assembly_base< Geometry > &assembly_base_, assembly< Geometry > &assembly_, FEBackend const &fe_backend_, MatrixType const &mass_)
Typedef Documentation
layout3_t
typedef layout_tt<3> gdl::intrepid::layout3_t
layout4_t
typedef layout_tt<4> gdl::intrepid::layout4_t
Function Documentation
test()
template<typename Geometry , typename FEBackend , typename MatrixType > bool gdl::intrepid::test (assembly_base< Geometry > & assembly_base_, assembly< Geometry > & assembly_, FEBackend const & fe_backend_, MatrixType const & stiffness_)
References d1, d2, d3, gdl::assembly_base< Geometry >::get_grid(), gdl::assembly< Geometry >::get_jac(), gdl::assembly< Geometry >::get_jac_det(), gdl::assembly< Geometry >::get_jac_inv(), gdl::assembly< Geometry >::m_d1, gdl::assembly< Geometry >::m_d2, and gdl::assembly< Geometry >::m_d3.
Referenced by main().
test_mass()
template<typename Geometry , typename FEBackend , typename MatrixType > bool gdl::intrepid::test_mass (assembly_base< Geometry > & assembly_base_, assembly< Geometry > & assembly_, FEBackend const & fe_backend_, MatrixType const & mass_)
References d1, d2, d3, gdl::assembly_base< Geometry >::get_grid(), gdl::assembly< Geometry >::get_jac(), gdl::assembly< Geometry >::get_jac_det(), gdl::assembly< Geometry >::m_d1, gdl::assembly< Geometry >::m_d2, and gdl::assembly< Geometry >::m_d3.
Referenced by main().