Galerkin4GT: /home/pol/src/GridTools/galerkin4gt_master/playground/IGA/RunTimeIGA/b_splines_basis_eval_test_rt.cpp File Reference
b_splines_basis_eval_test_rt.cpp File Reference
#include "b_splines_basis_rt.h"
#include <iostream>
#include <boost/mpl/vector.hpp>
#include <boost/shared_ptr.hpp>
#include <stencil-composition/stencil-composition.hpp>
Data Structures
struct bspline_basis_struct
Macros
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedefs
typedef interval< level< 0,-1 >, level< 1, 1 > > third_axis
typedef interval< level< 0,-1 >, level< 1,-1 > > x_lap
Functions
iga_rt::BSplineBasis< P, N > bspline_basis (knots)
int main ()
constexpr int N (5)
constexpr int NK (P+N+1)
constexpr int P (2)
Variables
constexpr const std::array< double, NK > knots {0,1,2,3,4,5,6,7}
Macro Definition Documentation
BACKEND
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedef Documentation
third_axis
typedef interval<level<0,-1>, level<1,1> > third_axis
x_lap
typedef interval<level<0,-1>, level<1,-1> > x_lap
Function Documentation
bspline_basis()
iga_rt::BSplineBasis<P,N> bspline_basis (knots)
Referenced by bspline_basis_struct::Do(), and main().
main()
int main ()
References bspline_basis(), and N().
N()
constexpr int N (5)
Referenced by bspline_basis_struct::Do(), gdl::functors::lax_friedrich< Geometry, Flux >::Do(), and main().
NK()
constexpr int NK (P+N+ 1)
P()
constexpr int P (2)
Referenced by gdl::functors::global_assemble::Do(), gdl::b_spline< order< P... > >::getCardinality(), gdl::b_spline< order< P... > >::getValues(), main(), and functors::main().
Variable Documentation
knots
constexpr const std::array<double, NK> knots {0,1,2,3,4,5,6,7}
Referenced by main(), and functors::main().