Galerkin4GT: /home/pol/src/GridTools/galerkin4gt_master/playground/IGA/RunTimeIGA/b_splines_eval_test_rt.cpp File Reference
b_splines_eval_test_rt.cpp File Reference
#include "b_splines_rt.h"
#include <vector>
#include <iostream>
#include <boost/mpl/vector.hpp>
#include <boost/shared_ptr.hpp>
#include <stencil-composition/stencil-composition.hpp>
Data Structures
struct bspline_struct
Macros
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedefs
typedef interval< level< 0,-1 >, level< 1, 1 > > third_axis
typedef interval< level< 0,-1 >, level< 1,-1 > > x_lap
Functions
iga_rt::BSpline< I, P > bspline (knots)
constexpr int I (2)
int main ()
constexpr int N (5)
constexpr int NK (P+N+1)
constexpr int P (2)
Variables
constexpr std::array< double, NK > knots {0,1,2,3,4,5,6}
Macro Definition Documentation
BACKEND
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedef Documentation
third_axis
typedef interval<level<0,-1>, level<1,1> > third_axis
x_lap
typedef interval<level<0,-1>, level<1,-1> > x_lap
Function Documentation
bspline()
iga_rt::BSpline<I,P> bspline (knots)
Referenced by bspline_struct::Do(), and main().
I()
constexpr int I (2)
Referenced by gdl::functors::bassi_rebay< Geometry >::Do(), gdl::functors::assign< 4, Value >::Do(), simple_gather< Geometry >::Do(), gdl::residual::Do(), gdl::functors::assign< 5, Value >::Do(), gdl::bc_functor::Do(), gdl::functors::lax_friedrich< Geometry, Flux >::Do(), gdl::functors::matvec::Do(), gdl::functors::matvec_VolxBdxVol::Do(), gdl::functors::matvec_BdxBdxBd::Do(), gdl::functors::assemble< Geometry >::Do(), gdl::functors::uniform< Geometry >::Do(), main(), gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1 >::operator()(), gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1, Range2, Range3 >::operator()(), gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range2, Range3 >::operator()(), and gdl::cg_solver< N_DOF0, N_DOF1, N_DOF2 >::solve_impl().
main()
int main ()
References bspline().
N()
constexpr int N (5)
NK()
constexpr int NK (P+N+ 1)
P()
constexpr int P (2)
Variable Documentation
knots
constexpr std::array<double, NK> knots {0,1,2,3,4,5,6}