Galerkin4GT: gdl Namespace Reference
gdl Namespace Reference
[assembly]
Namespaces
enumtype
functors
impl_
intrepid
Data Structures
struct aggregator_type_tuple
struct aggregator_type_tuple< assembly< Geometry >, Rest ... >
struct aggregator_type_tuple< assembly_base< Geometry >, Rest ... >
struct aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >
struct aggregator_type_tuple<>
struct assemble_storage
FEM assemble focused storage.
struct assembly
struct assembly_base
struct assembly_cg
struct assembly_dg
class b_spline
struct b_spline< order< P... > >
struct basis_select
struct basis_select< 1, enumtype::Lagrange, enumtype::Hexa >
struct basis_select< 1, enumtype::Lagrange, enumtype::Quad >
struct basis_select< 1, enumtype::Lagrange, enumtype::Tetra >
struct basis_select< 1, enumtype::Lagrange, enumtype::Tri >
struct basis_select< order, enumtype::Lagrange, enumtype::Hexa >
struct basis_select< order, enumtype::Lagrange, enumtype::Quad >
struct basis_select< order, enumtype::Lagrange, enumtype::Tetra >
struct basis_select< order, enumtype::Lagrange, enumtype::Tri >
struct basis_select< P, enumtype::Legendre, enumtype::Hexa >
struct basis_select< P, enumtype::Legendre, enumtype::Line >
struct basis_select< P, enumtype::Legendre, enumtype::Quad >
struct bc_apply
struct bc_functor
struct bd_assembly
Definition of the quantities needed for performing computations on the boundary.
struct boundary_cubature
[quadrature]
struct boundary_shape
struct boundary_shape< FE< Order, BasisType, enumtype::Hexa > >
struct boundary_shape< FE< Order, BasisType, enumtype::Line > >
struct boundary_shape< FE< Order, BasisType, enumtype::Quad > >
struct boundary_shape< FE< Order, BasisType, enumtype::Tetra > >
struct boundary_shape< FE< Order, BasisType, enumtype::Tri > >
struct BSplineCoeff
struct BSplineCoeff< Dim, order< P... >, I >
struct containing ID and polynomial order
struct BSplineDerived
just to ease the notation
struct cell
struct cg_solver
struct combinations
struct create_grid
struct create_grid< enumtype::rectilinear >
struct create_grid< enumtype::regular >
creates a regular grid
struct create_layout
struct create_layout< gt::gt_integer_sequence< ushort_t, Id ... > >
struct cubature
[quadrature]
struct evaluate_polynomial
struct evaluate_polynomial< 1, Order >
struct evaluate_polynomial< 2, Order >
struct evaluate_polynomial< 3, Order >
struct factorial
struct factorial< 0 >
class GenericBSpline
generic multivariate b-spline
struct get_val
struct global_to_local_dof_translator
Global to local dof translation struct.
struct grid_adjacency_rule_applier
class halo_data
Halo data storing structure.
struct hexa_grid_adjacency_rule_applier
struct integration
struct io_base
struct io_base< Derived< Storage, Args ... > >
struct io_rectilinear
I/O class for rectilinear grids, i.e. structured grid with elements of different sizes.
struct io_rectilinear< Storage, LocalGrid >
struct io_regular
struct io_regular< Storage >
struct legendre
struct linear_solver
struct nest_loop
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1, Range2, Range3 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range2, Range3 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, static_int< I >, Range3 >
struct order
struct pair_indexing
index pair to global position index translation struct
struct parametric_space
struct parametric_space< order< P ... > >
class holding the parametric space
struct reference_element
struct residual
struct shape_property
struct shape_property< enumtype::Hexa >
struct shape_property< enumtype::Line >
struct shape_property< enumtype::Point >
struct shape_property< enumtype::Quad >
struct shape_property< enumtype::Tetra >
struct shape_property< enumtype::Tri >
struct shape_select
struct shape_select< order, enumtype::Hexa >
struct shape_select< order, enumtype::Line >
struct shape_select< order, enumtype::Quad >
struct shape_select< order, enumtype::Tetra >
struct shape_select< order, enumtype::Tri >
struct tensor_product_element
struct zero
Typedefs
typedef gridtools::interval< gridtools::level< 0,-2 >, gridtools::level< 1, 1 > > axis
using float_type = gt::float_type
using int_t = gt::uint_t
template<ushort_t Dim>
using layout_tt = typename impl_::layout_from_dim< Dim >::layout_t
using short_t = gt::uint_t
template<int_t T>
using static_int = gt::static_int< T >
template<short_t T>
using static_short = gt::static_short< T >
template<uint_t T>
using static_uint = gt::static_uint< T >
template<ushort_t T>
using static_ushort = gt::static_ushort< T >
template<ushort_t ID, typename Layout , typename Aligned = gt::aligned<1>>
using storage_info = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::storage_info< ID, Layout, typename gt::repeat_template_c< 0, Layout::length, gt::halo >::type, Aligned >
template<typename ID , typename Layout , typename Aligned = gt::aligned<1>>
using storage_info_t = typename gt::meta_storage< gt::meta_storage_aligned< gt::meta_storage_base< ID, Layout, false >, Aligned, typename gt::repeat_template_c< 0, Layout::length, gt::halo >::type > >
template<typename MetaData >
using storage_t = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::storage_type< float_type, MetaData >::type
template<typename MetaData >
using tmp_storage_t = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::temporary_storage_type< float_type, MetaData >::type
using uint_t = gt::uint_t
using ushort_t = gt::uint_t
typedef gridtools::interval< gridtools::level< 0,-1 >, gridtools::level< 1,-1 > > x_interval
Functions
template<typename T >
constexpr gt::array< T, 3 > cross_product (gt::array< T, 3 > const &v1, gt::array< T, 3 > const &v2)
template<typename Storage , typename LocalGridInfo >
void reindex (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
Performing a copy of a scalar field into the provided data pointer.
template<ushort_t Face, typename Storage , typename LocalGridInfo >
void reindex_on_face (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
template<ushort_t CubDegree, typename Storage , typename Cubature >
void reindex_on_qpoints (Storage const &storage_, Cubature const &cubature_, typename Storage::value_type *data_)
template<typename Storage , typename LocalGridInfo >
void reindex_vec (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
constexpr float_type ricci (ushort_t const &i_, ushort_t const &j_)
[fe namespace]
constexpr float_type ricci (ushort_t const &i_, ushort_t const &j_, ushort_t const &k_)
template<typename Storage >
void spy (Storage const &storage_, char const *name)
export a matrix in matrix market format
template<typename Storage >
void spy_vec (Storage const &storage_, char const *name)
exports a vector
Detailed Description
[assembly]
[assembly] [boundary integration]
[includes]
Typedef Documentation
axis
typedef gridtools::interval<gridtools::level<0,-2>, gridtools::level<1,1> > gdl::axis
float_type
using gdl::float_type = typedef gt::float_type
int_t
using gdl::int_t = typedef gt::uint_t
layout_tt
template<ushort_t Dim> using gdl::layout_tt = typedef typename impl_::layout_from_dim< Dim >::layout_t
short_t
using gdl::short_t = typedef gt::uint_t
static_int
template<int_t T> using gdl::static_int = typedef gt::static_int<T>
static_short
template<short_t T> using gdl::static_short = typedef gt::static_short<T>
static_uint
template<uint_t T> using gdl::static_uint = typedef gt::static_uint<T>
static_ushort
template<ushort_t T> using gdl::static_ushort = typedef gt::static_ushort<T>
storage_info
template<ushort_t ID, typename Layout , typename Aligned = gt::aligned<1>> using gdl::storage_info = typedef typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype:: icosahedral , ::gdl::gt::enumtype::Naive > ::storage_info<ID, Layout, typename gt::repeat_template_c<0, Layout::length, gt::halo>::type, Aligned>
storage_info_t
template<typename ID , typename Layout , typename Aligned = gt::aligned<1>> using gdl::storage_info_t = typedef typename gt::meta_storage<gt::meta_storage_aligned<gt::meta_storage_base<ID, Layout, false>, Aligned, typename gt::repeat_template_c<0, Layout::length, gt::halo>::type > >
storage_t
template<typename MetaData > using gdl::storage_t = typedef typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype:: icosahedral , ::gdl::gt::enumtype::Naive > ::storage_type<float_type, MetaData >::type
tmp_storage_t
template<typename MetaData > using gdl::tmp_storage_t = typedef typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype:: icosahedral , ::gdl::gt::enumtype::Naive > ::temporary_storage_type<float_type, MetaData >::type
uint_t
using gdl::uint_t = typedef gt::uint_t
Examples:
poisson.cpp.
ushort_t
using gdl::ushort_t = typedef gt::uint_t
x_interval
typedef gridtools::interval<gridtools::level<0,-1>, gridtools::level<1,-1> > gdl::x_interval
Function Documentation
cross_product()
template<typename T > constexpr gt::array<T, 3> gdl::cross_product (gt::array< T, 3 > const & v1, gt::array< T, 3 > const & v2)
compute vector product
References ricci().
Referenced by gdl::intrepid::boundary_discr< bd_cub_t >::compute_normals().
reindex()
template<typename Storage , typename LocalGridInfo > void gdl::reindex (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of a scalar field into the provided data pointer.
Note
: unsafe
References d1, d2, d3, and d4.
Referenced by gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_scalar().
reindex_on_face()
template<ushort_t Face, typename Storage , typename LocalGridInfo > void gdl::reindex_on_face (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of all the dofs on faces 0, 2 ,4, in order to fix the memory layout
References d1, d2, d3, and d4.
reindex_on_qpoints()
template<ushort_t CubDegree, typename Storage , typename Cubature > void gdl::reindex_on_qpoints (Storage const & storage_, Cubature const & cubature_, typename Storage::value_type * data_)
Performing a copy of all the quadrature points, in order to fix the memory layout
References d1, d2, d3, and d4.
reindex_vec()
template<typename Storage , typename LocalGridInfo > void gdl::reindex_vec (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
This is needed in order to write the vector to the output file
References d1, d2, d3, and d4.
Referenced by gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_vector().
ricci() [1/2]
constexpr float_type gdl::ricci (ushort_t const & i_, ushort_t const & j_)
[fe namespace]
compute ricci symbol
Referenced by cross_product(), and ricci().
ricci() [2/2]
constexpr float_type gdl::ricci (ushort_t const & i_, ushort_t const & j_, ushort_t const & k_)
References ricci().
spy()
template<typename Storage > void gdl::spy (Storage const & storage_, char const * name)
export a matrix in matrix market format
This function writes a matrix to a text file in matrix market format. This format can be loaded by Matlab/Octave to see the matrix pattern, and it is a specific format for sparse matrices. It consists of lines with 3 entries: the first 2 for the i,j coordinates, and the third for the nonzero matrix value.
References d1, d2, d3, and d4.
Referenced by main().
spy_vec()
template<typename Storage > void gdl::spy_vec (Storage const & storage_, char const * name)
exports a vector
this function writes out a vector in text format, in a newline-separated list which can be loaded (e.g.) by Matlab/Octave
References d1, d2, d3, and d4.
Referenced by main().