Galerkin4GT: gdl Namespace Reference
gdl Namespace Reference
[assembly]
Data Structures
struct aggregator_type_tuple
struct aggregator_type_tuple< assembly< Geometry >, Rest ... >
struct aggregator_type_tuple
struct aggregator_type_tuple< assembly_base< Geometry >, Rest ... >
struct aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >
struct aggregator_type_tuple<>
struct assemble_storage
FEM assemble focused storage.
struct assembly
aggregator of tools and storages used to assemble the finite elements discretization of the most common operators
struct assembly_base
struct containing the grid information
struct assembly_cg
struct assembly_dg
class b_spline
struct b_spline< order< P... > >
struct basis_select
struct basis_select< 1, enumtype::Lagrange, enumtype::Hexa >
struct basis_select< 1, enumtype::Lagrange, enumtype::Quad >
struct basis_select< 1, enumtype::Lagrange, enumtype::Tetra >
struct basis_select< 1, enumtype::Lagrange, enumtype::Tri >
struct basis_select< order, enumtype::Lagrange, enumtype::Hexa >
struct basis_select< order, enumtype::Lagrange, enumtype::Quad >
struct basis_select< order, enumtype::Lagrange, enumtype::Tetra >
struct basis_select< order, enumtype::Lagrange, enumtype::Tri >
struct basis_select< P, enumtype::Legendre, enumtype::Hexa >
struct basis_select< P, enumtype::Legendre, enumtype::Line >
struct basis_select< P, enumtype::Legendre, enumtype::Quad >
struct bc_apply
struct bc_functor
struct bd_assembly
Definition of the quantities needed for performing computations on the boundary.
struct boundary_cubature
struct boundary_shape
struct boundary_shape< FE< Order, BasisType, enumtype::Hexa > >
struct boundary_shape< FE< Order, BasisType, enumtype::Line > >
struct boundary_shape< FE< Order, BasisType, enumtype::Quad > >
struct boundary_shape< FE< Order, BasisType, enumtype::Tetra > >
struct boundary_shape< FE< Order, BasisType, enumtype::Tri > >
struct BSplineCoeff
struct BSplineCoeff< Dim, order< P... >, I >
struct containing ID and polynomial order
struct BSplineDerived
just to ease the notation
struct cell
struct cg_solver
struct combinations
struct create_grid
struct create_grid< enumtype::rectilinear >
struct create_grid< enumtype::regular >
creates a regular grid
struct create_layout
metafunction for creating a gridtools::layout_map
struct create_layout< gt::gt_integer_sequence< ushort_t, Id ... > >
struct cubature
representation of the cubature rule
struct evaluate_polynomial
helper metafunction to evaluate a multivariate polynomial of a given order (trivariate case)
struct evaluate_polynomial< 1, Order >
struct evaluate_polynomial< 2, Order >
helper metafunction to evaluate a multivariate polynomial of a given order (bivariate case)
struct evaluate_polynomial< 3, Order >
helper metafunction to evaluate a multivariate polynomial of a given order (trivariate case)
struct factorial
struct factorial< 0 >
class GenericBSpline
generic multivariate b-spline
struct get_val
struct global_to_local_dof_translator
Global to local dof translation struct.
struct grid_adjacency_rule_applier
class halo_data
Halo data storing structure.
struct hexa_grid_adjacency_rule_applier
struct integration
struct io_base
struct io_base< Derived< Storage, Args ... > >
struct io_rectilinear
I/O class for rectilinear grids, i.e. structured grid with elements of different sizes.
struct io_rectilinear< Storage, LocalGrid >
struct io_regular
struct io_regular< Storage >
struct legendre
implementation of Legendre basis functions in 2D and 3D
struct linear_solver
struct nest_loop
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1, Range2, Range3 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range2, Range3 >
struct nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, static_int< I >, Range3 >
struct order
struct pair_indexing
index pair to global position index translation struct
struct parametric_space
struct parametric_space< order< P ... > >
class holding the parametric space
struct reference_element
class containing information about the reference element
struct residual
struct shape_property
struct shape_property< enumtype::Hexa >
struct shape_property< enumtype::Line >
struct shape_property< enumtype::Point >
struct shape_property< enumtype::Quad >
struct shape_property< enumtype::Tetra >
struct shape_property< enumtype::Tri >
struct shape_select
struct shape_select< order, enumtype::Hexa >
struct shape_select< order, enumtype::Line >
struct shape_select< order, enumtype::Quad >
struct shape_select< order, enumtype::Tetra >
struct shape_select< order, enumtype::Tri >
struct tensor_product_element
struct zero
Typedefs
typedef gridtools::interval< gridtools::level< 0,-2 >, gridtools::level< 1, 1 > > axis
using float_type = gt::float_type
using int_t = gt::uint_t
template<ushort_t Dim>
using layout_tt = typename impl_::layout_from_dim< Dim >::layout_t
Metafunction generating the layout_map with the appropriate order of the dimensions (increasing for CPU, decreasing for GPU)
using short_t = gt::uint_t
template<int_t T>
using static_int = gt::static_int< T >
template<short_t T>
using static_short = gt::static_short< T >
template<uint_t T>
using static_uint = gt::static_uint< T >
template<ushort_t T>
using static_ushort = gt::static_ushort< T >
template<ushort_t ID, typename Layout , typename Aligned = gt::aligned<1>>
using storage_info = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::storage_info< ID, Layout, typename gt::repeat_template_c< 0, Layout::length, gt::halo >::type, Aligned >
template<typename ID , typename Layout , typename Aligned = gt::aligned<1>>
using storage_info_t = typename gt::meta_storage< gt::meta_storage_aligned< gt::meta_storage_base< ID, Layout, false >, Aligned, typename gt::repeat_template_c< 0, Layout::length, gt::halo >::type > >
template<typename MetaData >
using storage_t = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::storage_type< float_type, MetaData >::type
template<typename MetaData >
using tmp_storage_t = typename ::gdl::gt::backend<::gdl::gt::enumtype::Host, ::gdl::gt::enumtype::icosahedral, ::gdl::gt::enumtype::Naive > ::temporary_storage_type< float_type, MetaData >::type
using uint_t = gt::uint_t
using ushort_t = gt::uint_t
typedef gridtools::interval< gridtools::level< 0,-1 >, gridtools::level< 1,-1 > > x_interval
Functions
template<typename T >
constexpr gt::array< T, 3 > cross_product (gt::array< T, 3 > const &v1, gt::array< T, 3 > const &v2)
compute vector cross product
template<typename Storage , typename LocalGridInfo >
void reindex (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
Performing a copy of a scalar field into the provided data pointer.
template<ushort_t Face, typename Storage , typename LocalGridInfo >
void reindex_on_face (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
template<ushort_t CubDegree, typename Storage , typename Cubature >
void reindex_on_qpoints (Storage const &storage_, Cubature const &cubature_, typename Storage::value_type *data_)
template<typename Storage , typename LocalGridInfo >
void reindex_vec (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
constexpr float_type ricci (ushort_t const &i_, ushort_t const &j_)
compute Ricci symbol
constexpr float_type ricci (ushort_t const &i_, ushort_t const &j_, ushort_t const &k_)
compute Ricci symbol
template<typename Storage >
void spy (Storage const &storage_, char const *name)
export a matrix in matrix market format
template<typename Storage >
void spy_vec (Storage const &storage_, char const *name)
exports a vector
Detailed Description
[assembly]
[assembly] [boundary integration]
Function Documentation
cross_product()
template<typename T > constexpr gt::array<T, 3> gdl::cross_product (gt::array< T, 3 > const & v1, gt::array< T, 3 > const & v2)
compute vector cross product
Parameters
v1 left operand
v2 right operand
References ricci().
Referenced by gdl::intrepid::boundary_discr< bd_cub_t >::compute_normals().
reindex()
template<typename Storage , typename LocalGridInfo > void gdl::reindex (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of a scalar field into the provided data pointer.
Note
unsafe
Referenced by gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_scalar().
reindex_on_face()
template<ushort_t Face, typename Storage , typename LocalGridInfo > void gdl::reindex_on_face (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of all the dofs on faces 0, 2 ,4, in order to fix the memory layout
reindex_on_qpoints()
template<ushort_t CubDegree, typename Storage , typename Cubature > void gdl::reindex_on_qpoints (Storage const & storage_, Cubature const & cubature_, typename Storage::value_type * data_)
Performing a copy of all the quadrature points, in order to fix the memory layout
reindex_vec()
template<typename Storage , typename LocalGridInfo > void gdl::reindex_vec (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
This is needed in order to write the vector to the output file
Referenced by gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_vector().
spy()
template<typename Storage > void gdl::spy (Storage const & storage_, char const * name)
export a matrix in matrix market format
This function writes a matrix to a text file in matrix market format. This format can be loaded by Matlab/Octave to see the matrix pattern, and it is a specific format for sparse matrices. It consists of lines with 3 entries: the first 2 for the i,j coordinates, and the third for the nonzero matrix value.
Examples:
dg_advection.cpp.
spy_vec()
template<typename Storage > void gdl::spy_vec (Storage const & storage_, char const * name)
exports a vector
this function writes out a vector in text format, in a newline-separated list which can be loaded (e.g.) by Matlab/Octave
Examples:
dg_advection.cpp.